# Generated by Django 6.1 on 2026-08-19 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_documentos', '0003_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='Version')),
                ('contenido_markdown', models.TextField(verbose_name='Contenido markdown')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Version de documento',
                'verbose_name_plural': 'Versiones de documento',
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='extension_original',
            field=models.CharField(default='', max_length=10, verbose_name='Extension original'),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion'),
        ),
        migrations.AddConstraint(
            model_name='documento',
            constraint=models.UniqueConstraint(fields=('proyecto', 'carpeta', 'nombre'), name='unique_documento_por_carpeta'),
        ),
        migrations.AddField(
            model_name='documentoversion',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='gestor_documentos.documento'),
        ),
        migrations.AddConstraint(
            model_name='documentoversion',
            constraint=models.UniqueConstraint(fields=('documento', 'version'), name='unique_version_por_documento'),
        ),
    ]
