# Generated by Django 5.2.5 on 2026-08-19 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_documentos', '0005_carpeta_created_by_carpeta_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('proyecto_creado', 'Proyecto creado'), ('carpeta_creada', 'Carpeta creada'), ('documento_subido', 'Documento subido'), ('documento_modificado', 'Documento modificado')], max_length=40)),
                ('titulo', models.CharField(max_length=255)),
                ('detalle', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_actividad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacion de actividad',
                'verbose_name_plural': 'Notificaciones de actividad',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
