# Generated by Django 5.2.5 on 2026-08-19 09:38

import django.db.models.deletion
import gestor_documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_documentos', '0006_alter_carpeta_id_alter_documento_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionactividad',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacionactividad',
            name='tipo',
            field=models.CharField(choices=[('proyecto_creado', 'Proyecto creado'), ('carpeta_creada', 'Carpeta creada'), ('documento_subido', 'Documento subido'), ('documento_modificado', 'Documento modificado'), ('ticket_creado', 'Ticket creado'), ('ticket_cerrado', 'Ticket cerrado')], max_length=40),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_secuencial', models.PositiveIntegerField(unique=True)),
                ('numero_ticket', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('carpeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='gestor_documentos.carpeta')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_cerrados', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_creados', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='gestor_documentos.documento')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='gestor_documentos.proyecto')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TicketAdjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=gestor_documentos.models.ticket_attachment_upload_to)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_ticket_creados', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='gestor_documentos.ticket')),
            ],
            options={
                'verbose_name': 'Adjunto de ticket',
                'verbose_name_plural': 'Adjuntos de ticket',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TicketComentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_ticket_creados', to=settings.AUTH_USER_MODEL)),
                ('documento_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_ticket', to='gestor_documentos.documentoversion')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='gestor_documentos.ticket')),
            ],
            options={
                'verbose_name': 'Comentario de ticket',
                'verbose_name_plural': 'Comentarios de ticket',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
