# Generated by Django 5.2.5 on 2026-08-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_documentos', '0007_notificacionactividad_destinatario_alter_carpeta_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentoversion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
