# Generated by Django 5.2.5 on 2026-08-19 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_documentos', '0008_alter_carpeta_id_alter_documento_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionLeida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='gestor_documentos.notificacionactividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_leidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacion leida',
                'verbose_name_plural': 'Notificaciones leidas',
                'ordering': ['-fecha_creacion'],
                'constraints': [models.UniqueConstraint(fields=('notificacion', 'usuario'), name='unique_notificacion_leida_por_usuario')],
            },
        ),
    ]
