# Generated by Django 5.2.5 on 2026-08-19 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_documentos', '0009_notificacionleida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketcomentario',
            name='tipo',
            field=models.CharField(choices=[('mensaje', 'Mensaje'), ('respuesta_gestor', 'Respuesta de gestor'), ('rechazo_usuario', 'Revision rechazada'), ('aceptacion_usuario', 'Revision aceptada')], default='mensaje', max_length=30),
        ),
        migrations.AlterField(
            model_name='notificacionactividad',
            name='tipo',
            field=models.CharField(choices=[('proyecto_creado', 'Proyecto creado'), ('carpeta_creada', 'Carpeta creada'), ('documento_subido', 'Documento subido'), ('documento_modificado', 'Documento modificado'), ('ticket_creado', 'Ticket creado'), ('ticket_cerrado', 'Ticket cerrado'), ('ticket_revision', 'Ticket en revision'), ('ticket_reabierto', 'Ticket reabierto')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('en_revision', 'En revision de usuario'), ('cerrado', 'Cerrado')], default='abierto', max_length=20),
        ),
    ]
