# Generated by Django 5.2.5 on 2026-08-19 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_documentos', '0010_ticket_fecha_revision_ticket_reviewed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionactividad',
            name='tipo',
            field=models.CharField(choices=[('proyecto_creado', 'Proyecto creado'), ('carpeta_creada', 'Carpeta creada'), ('documento_subido', 'Documento subido'), ('documento_modificado', 'Documento modificado'), ('documento_revisado', 'Documento revisado'), ('ticket_creado', 'Ticket creado'), ('ticket_cerrado', 'Ticket cerrado'), ('ticket_revision', 'Ticket en revision'), ('ticket_reabierto', 'Ticket reabierto')], max_length=40),
        ),
        migrations.CreateModel(
            name='DocumentoRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_documento_creadas', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='gestor_documentos.documento')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='gestor_documentos.documentoversion')),
            ],
            options={
                'verbose_name': 'Revision de documento',
                'verbose_name_plural': 'Revisiones de documento',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
