# Generated by Django 5.2.5 on 2026-08-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_documentos', '0012_sistemaconfiguracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemaconfiguracion',
            name='github_owner',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sistemaconfiguracion',
            name='github_repo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
