# Generated by Django 6.1 on 2026-08-19 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_documentos', '0014_wbsetapa_wbstarea_wbscomentario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WbsProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de proyecto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto WBS',
                'verbose_name_plural': 'Proyectos WBS',
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='wbsetapa',
            name='unique_wbs_etapa_nombre',
        ),
        migrations.AddField(
            model_name='wbsproyecto',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wbs_proyectos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wbsproyecto',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wbs_proyectos_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wbsetapa',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='gestor_documentos.wbsproyecto'),
        ),
        migrations.AddConstraint(
            model_name='wbsetapa',
            constraint=models.UniqueConstraint(fields=('proyecto', 'nombre'), name='unique_wbs_etapa_nombre_por_proyecto'),
        ),
        migrations.AddConstraint(
            model_name='wbsproyecto',
            constraint=models.UniqueConstraint(fields=('nombre',), name='unique_wbs_proyecto_nombre'),
        ),
    ]
