# Generated by Django 6.1 on 2026-08-19 22:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_documentos', '0015_wbsproyecto_remove_wbsetapa_unique_wbs_etapa_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wbsproyecto',
            name='prefijo',
            field=models.CharField(default='', max_length=20, verbose_name='Prefijo'),
        ),
        migrations.AddField(
            model_name='wbstarea',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='wbstarea',
            name='numero_secuencial',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='wbsproyecto',
            constraint=models.UniqueConstraint(fields=('prefijo',), name='unique_wbs_proyecto_prefijo'),
        ),
    ]
