# Generated by Django 6.1 on 2026-08-19 22:24

import django.db.models.deletion
import gestor_documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_documentos', '0016_wbsproyecto_prefijo_wbstarea_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WbsAdjuntoImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=gestor_documentos.models.wbs_task_image_upload_to)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wbs_adjuntos_creados', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='gestor_documentos.wbstarea')),
            ],
            options={
                'verbose_name': 'Adjunto de imagen WBS',
                'verbose_name_plural': 'Adjuntos de imagen WBS',
                'ordering': ['fecha_creacion', 'id'],
            },
        ),
    ]
