# Generated by Django 5.2.5 on 2026-08-19 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_documentos', '0019_wbssubtarea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WbsDependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wbs_dependencias_creadas', to=settings.AUTH_USER_MODEL)),
                ('depende_de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_bloqueadas', to='gestor_documentos.wbstarea')),
                ('etapa_inicial_dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias_iniciales', to='gestor_documentos.wbsetapa')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias', to='gestor_documentos.wbstarea')),
            ],
            options={
                'verbose_name': 'Dependencia WBS',
                'verbose_name_plural': 'Dependencias WBS',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('tarea', 'depende_de'), name='unique_wbs_dependencia_por_tarea'), models.CheckConstraint(condition=models.Q(('tarea', models.F('depende_de')), _negated=True), name='wbs_dependencia_no_self')],
            },
        ),
    ]
